---
version: '3'

vars:
  APP_DIR: "./src"
  CONFIG_DIR: "./example_config"
  CONTAINER_NAME: "telegrammy"

tasks:
  default:
    desc: Build and run telegrammy in Docker container
    aliases: [run]
    deps:
      - build
    cmds:
      - |
        docker run \
          -e TELEGRAMMY_CONFIG_PATH="{{.TELEGRAMMY_CONFIG_PATH}}" \
          -e TELEGRAM_CHAT_ID="{{.TELEGRAM_CHAT_ID}}" \
          -e TELEGRAM_BOT_TOKEN="{{.TELEGRAM_BOT_TOKEN}}" \
          -e CHAT_GPT_TOKEN="{{.CHAT_GPT_TOKEN}}" \
          -e CHAT_GPT_CONVERSATION_PATH="{{.CHAT_GPT_CONVERSATION_PATH}}" \
          -v "{{.CONFIG_DIR}}:/etc/telegrammy:z" \
          telegrammy
    silent: true

  build:
    desc: Build telegrammy Docker image
    cmds:
      - docker build {{.APP_DIR}} -t telegrammy
    silent: true
